version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    expose:
      - 1883
      - 8000
      - 8080
    ports:
      - "1883:1883"
      - "9090:9090"
    volumes:
      - ./compose/mosquitto/conf:/mosquitto/config
      - ./compose/mosquitto/data:/mosquitto/data
      - ./compose/mosquitto/log:/mosquitto/log
  neo4j:
    image: neo4j:4.4.4
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
#    depends_on:
#      - kafka
    volumes:
      - ./compose/neo4j/data:/data
      - ./compose/neo4j/plugins:/plugins
      - ./compose/neo4j/import:/import
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_logs_debug_level=DEBUG
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=neo4j/test
volumes:
  neo4j: